### ISSUE TITLE
⛔ Can't access Client Directory 📂 on Github

### ISSUE THREAD

**Issue by vikas-vimal** [WebDevSimplified/google-docs-clone#1]
**Client** folder is not clickable in the repo 👎... **Server** folder is accessible 👍.

**Comment by TechStudent10** [comment]
yeah. I can't open the client folder also.

**Comment by TechStudent10** [comment]
But I can open the server one.

**Comment by bryanakitchen** [comment]
I noticed that as well.  In the meantime, feel free to check out my repos (below). I followed along and added some comments as well.

Edit: After hosting with Heroku and Netlify, I had to separate my repo into two repos: [front](https://github.com/bryanakitchen/google-docs-clone-front) and [back](https://github.com/bryanakitchen/google-docs-clone-server).

**Comment by Bunty9** [comment]
looks like the client folder is empty 
@WebDevSimplified please commit client side 🙏🏻🙏🏻

**Comment by WebDevSimplified** [comment]
Sorry about that! I just added it in so you should be able to access it now.
